name: mini_rpg
description: "MiniRPG"
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  polymer: any
  core_elements: any
  paper_elements: ">=0.0.1 <0.1.0"
  web_components: ">=0.3.5-dev.3 <0.4.0"
#  pixi:
#      path: dist/Pixi.dart/

environment:
  sdk: ">=0.8.10+6 <2.0.0"
transformers:
- polymer:
    entry_points: web/index.html
